name: Deploy Nginx

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Nginx
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx

      - name: Start Nginx
        run: sudo systemctl start nginx

      - name: Set up default website
        run: |
          echo "<!DOCTYPE html>
          <html>
          <head>
              <title>Welcome to Nginx!</title>
          </head>
          <body>
              <h1>Success! The Nginx server is working!</h1>
          </body>
          </html>" | sudo tee /var/www/html/index.html

      - name: Restart Nginx
        run: sudo systemctl restart nginx

      - name: Verify Nginx status
        run: sudo systemctl status nginx
