name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  run-nginx:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Nginx
      run: |
        docker run -d -p 80:80 nginx
        docker ps
