name: Установить nginx

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Установить nginx
        run: |
          sudo apt update && sudo apt install nginx

      - name: Создать файл конфигурации nginx
        run: |
          sudo touch /etc/nginx/sites-available/default

      - name: Изменить права доступа к файлу конфигурации nginx
        run: |
          sudo chmod 777 /etc/nginx/sites-available/default

      - name: Добавить контент в файл конфигурации nginx
        run: |
          echo "server {
            listen 80;
            server_name localhost;
            location / {
              root /usr/share/nginx/html;
              index index.html;
            }
          }" > /etc/nginx/sites-available/default

      - name: Изменить права доступа к файлу конфигурации nginx_2
        run: |
          sudo chmod 644 /etc/nginx/sites-available/default
        
      - name: Включить файл конфигурации nginx
        run: |
          sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

      - name: Перезапустить nginx
        run: |
          sudo service nginx restart

      - name: Проверить работоспособность nginx
        run: |
          curl localhost
