name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
 build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to GitLab Container Registry
      run: echo "${{ secrets.CI_REGISTRY_PASSWORD }}" | docker login ${{ secrets.CI_REGISTRY }} -u ${{ secrets.CI_REGISTRY_USER }} --password-stdin

    - name: Build Docker image
      run: docker build -t registry.gitlab.com/luferius1/moneylong .

    - name: Run Docker container
      run: docker run -d -p 8081:80 registry.gitlab.com/luferius1/moneylong
