name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.9

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5.3.0
        with:
          image: pachyderm/python-build
          registry: docker.io
