name: nginx

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: install_nginx
      run: |
        sudo apt-get update
        sudo apt-get install nginx

    - name: nginx
      run: |
        echo "server {
          listen 80;
          server_name example.com;
          location / {
            root /var/www/html;
            index index.html;
          }
        }" > nginx.conf
        sudo cp nginx.conf /etc/nginx/sites-available/

    - name: Nginx
      run: |
        sudo ln -s /etc/nginx/sites-available/nginx.conf /etc/nginx/sites-enabled/

    - name: reload Nginx
      run: |
        sudo service nginx restart
