name: Run Nginx in Docker

on: [push]

jobs:
  run-nginx:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Nginx Docker image
      run: docker build -t my-nginx .

    - name: Run Nginx container
      run: docker run -d -p 80:80 my-nginx
      
    - name: Check Nginx
      run: |
        docker ps
        curl http://localhost

